### ISSUE TITLE
Sync Dropbox to Nextcloud

### ISSUE THREAD

**Issue by ilizid** [eneiluj/integration_dropbox#11]
i have a question about the Dropbox integration on Nextcloud Server, once i have imported all files and ill change some in Dropbox, will Nextcloud automatically sync the files from DB to NC over?

**Comment by eneiluj** [comment]
Sorry for the late answer.
This is a basic one way sync. If you launch the import again after having:
* just made changes inside a DB file, it will not import it again in NC
* deleted a DB file, it will not delete it on NC side
* added a file, it will get it in NC

The import process works more or less like that:
```
For every file in DB:
    if it exists in NC:
        do nothing
    else:
        get it
```

Feel free to reopen the issue if you have more questions.
