### ISSUE TITLE
Settings Screen won't come up vue errors

### ISSUE THREAD

**Issue by janesser** [eneiluj/integration_dropbox#4]
Just installed nextcloud on raspberry 400, also installed dropbox-integration, but i fail to setup this app.

It is unsecure local http connection so far.

![2020-12-19-121524_1440x900_scrot](https://user-images.githubusercontent.com/7354047/102687995-ec2a8500-41f3-11eb-9456-1fdad9edb31a.png)

Versions:
pi@raspberrypi:~ $ snap list
Name       Version      Rev    Tracking       Publisher   Notes
core       16-2.48      10579  latest/stable  canonical✓  core
core18     20201210     1948   latest/stable  canonical✓  base
nextcloud  20.0.3snap1  24942  latest/stable  nextcloud✓  -

Dropbox integration	0.0.7

Chromium: Version 86.0.4240.197 (Offizieller Build) Built on Raspbian , running on Raspbian 10 (32-Bit)

**Comment by beniaminrychter** [comment]
Hi! I'm having exactly same issue. 
I'm using NextCloud on Docker on RPi4. Connecting to instance as well by unsecure HTTP inside my local network.

**Comment by eneiluj** [comment]
Thanks for the bug report. The browser detection is failing in your context. It is not used anyway so I removed it in v0.0.13 which was just released. Could you try it and tell me if it works now?

Thanks to your bug report I now know I have to fix browser detection in every integration app that actually uses it.

**Comment by janesser** [comment]
@eneiluj checked the new version. works like a charm. big kudos!
