### ISSUE TITLE
App only show connection status

### ISSUE THREAD

**Issue by manuel140** [eneiluj/integration_dropbox#5]
Hi, i've installed the app and connected it to my Dropbox account. 
After that it doesn't show anything but the connection (see image attached).

Am i doing something wrong?

![image](https://user-images.githubusercontent.com/3961799/102808943-7116c980-43c1-11eb-91f8-3b9c3d10fffc.png)

**Comment by eneiluj** [comment]
Hi, I don't think you're doing anything wrong :grin:. There must be an error somewhere. Do you see something in the browser console log (F12 -> Console)?

**Comment by manuel140** [comment]
Hi @eneiluj, there are no errors (just jQuery deprecation warnings which i filtered).

![image](https://user-images.githubusercontent.com/3961799/102871685-00ae8d80-443f-11eb-8217-bc91e617e9f9.png)

**Comment by eneiluj** [comment]
Then another possible reason is that your dropbox storage is empty. Is it?

If it's not empty, could you check the response of the request which URL is ending with `storage-size`? This can be found in the "network" tab, same place as the console.

**Comment by manuel140** [comment]
My Dropbox is not empty. :)

The storage-size request ist pending for 10 minutes now. 
No errors.

![image](https://user-images.githubusercontent.com/3961799/102877878-b7af0700-4447-11eb-9532-a290d2bc9a15.png)

**Comment by manuel140** [comment]
After nearly 20 minutes i received something :)

![image](https://user-images.githubusercontent.com/3961799/102878729-ff825e00-4448-11eb-9460-813bd2eba812.png)

**Comment by manuel140** [comment]
It's now showing the Import button. 
Trying to import the files. 

Thank you @eneiluj!

**Comment by eneiluj** [comment]
Could you check what's the response content? Just select the request line and go to "Response" tab. It should show you something like
```
usageInStorage: xxx,
nbFiles: xxx,
```

**Comment by manuel140** [comment]
Oh i'm sorry, i just closed the Task. 
There are like 270GB on the Dropbox and about 700.000 Files. 
I will start the Request again and post the Screenshot later.

**Comment by manuel140** [comment]
Request took 19 minutes again.
![image](https://user-images.githubusercontent.com/3961799/102881874-cd272f80-444d-11eb-96e7-71574fd7e64f.png)

But it seems like it's importing files now. 👍

**Comment by eneiluj** [comment]
There is clearly a bottleneck here. I'll improve that soon. Thanks a lot for the feedback. I'll keep you informed.

In the meantime, you can stop the import which will take a very long time since you will loose 20 minutes on each import job...

**Comment by manuel140** [comment]
The import job seems to run much quicker. 
There is an update every couple seconds. 
![image](https://user-images.githubusercontent.com/3961799/102882858-5a1eb880-444f-11eb-9f30-9cfe0a129c13.png)

**Comment by eneiluj** [comment]
v0.0.8 is out. With this release, storage size information is going to be much faster (less than one second) because it does not count the files anymore. This counting operation was listing files by chunks of 2000 which means it was doing a huge number of requests to get a list of all your files. That's why it took 20 minutes.

Files were also counted each time an import background job was launched. This is not the case anymore.

My advice for you is to stop the import, upgrade the app and launch the import again.

**Comment by manuel140** [comment]
Thank you very much! 
The storage-size request is much faster now!

**Comment by eneiluj** [comment]
Thanks for your enthusiasm. I'm interested to know if everything was imported successfully on your side.

A little more details about the file count issue. Dropbox API does not provide a way to get the total file number on a storage. I thought counting them by listing directories content would be fast enough...but apparently it's really not. Thanks again for reporting your issue.
